class AutismDiagnosticQuestions {
  static List<String> srs2Questions() {
    return [
      'I notice small changes in the way a person talks or acts.',
      'I find it difficult to maintain eye contact with others.',
      'I am able to read between the lines when someone is talking to me.',
      'I get upset if my daily routine is altered.',
      'I find it difficult to understand people’s facial expressions.',
      'I find it easy to interact with people in social settings.',
      'I avoid situations that involve a lot of social interaction.',
      'I have trouble understanding jokes or sarcasm.',
      'I prefer to be alone rather than with others.',
      'I find it challenging to adjust to new social environments.',
      'I have difficulty sharing my emotions with others.',
      'I get lost in the details of what others are saying.',
      'I often miss social cues in conversations.',
      'I prefer routines and find comfort in sticking to them.',
      'I find it hard to figure out what others are thinking or feeling.',
      'I prefer to talk about specific topics of interest to me rather than a range of topics.',
      'I get anxious in social situations where I don’t know what to expect.',
      'I have difficulty understanding non-verbal communication, like gestures or tone of voice.',
      'I avoid eye contact when I talk to people.',
      'I have a hard time understanding people’s intentions.',
      'I find it easier to communicate with people one-on-one rather than in a group.',
      'I struggle with understanding abstract or implied meanings in conversations.',
      'I feel overwhelmed when there’s a lot of social or sensory input.',
      'I find it difficult to switch from one activity to another.',
      'I often find social rules confusing and hard to follow.',
      'I have trouble understanding body language.',
      'I find social situations exhausting.',
      'I am good at focusing on tasks that require attention to detail.',
      'I get irritated when my schedule changes suddenly.',
      'I find it hard to make and keep friends.',
      'I often feel misunderstood in social interactions.',
      'I have difficulty keeping up with conversations in groups.',
      'I find it challenging to know when it’s my turn to speak in a conversation.',
      'I avoid participating in activities that involve other people.',
      'I prefer factual information over fiction or stories that are open to interpretation.',
      'I feel stressed when interacting with people I don’t know well.',
      'I have difficulty understanding why people act the way they do.',
      'I enjoy repetitive activities and find them comforting.',
      'I find it difficult to engage in small talk.',
      'I struggle with responding appropriately in social situations.',
      'I feel awkward in social interactions, especially in larger groups.',
      'I get frustrated when things don’t go as planned or as expected.',
      'I tend to focus on one aspect of a conversation and miss other important points.',
      'I prefer to follow a strict schedule and feel unsettled when things change.',
      'I find it hard to guess what other people expect from me.',
      'I struggle with understanding humor or irony in conversations.',
      'I feel more comfortable following clear, structured activities.',
      'I avoid situations that require me to interact with unfamiliar people.',
      'I tend to interpret language literally and struggle with figurative speech.',
    ];
  }

  static List<String> mCharQuestions() {
    return [
      'Does your child enjoy being swung, bounced on your knee, etc.?',
      'Does your child take an interest in other children?',
      'Does your child like climbing on things, such as furniture, playground equipment, or stairs?',
      'Does your child enjoy playing peek-a-boo or hide-and-seek?',
      'Does your child ever pretend, for example, to talk on the phone or take care of dolls or pretend other things?',
      'Does your child ever use his/her index finger to point, to ask for something?',
      'Does your child ever use his/her index finger to point, to indicate interest in something?',
      'Can your child play properly with small toys (e.g. cars or bricks) without just mouthing, fiddling, or dropping them?',
      'Does your child ever bring objects over to you (parent) to show you something?',
      'Does your child look you in the eye for more than a second or two?',
      'Does your child ever seem oversensitive to noise (e.g., plugging ears)?',
      'Does your child smile in response to your face or your smile?',
      'Does your child imitate you (e.g., you make a face—will your child imitate it)?',
      'Does your child respond to his/her name when you call?',
      'If you point at a toy across the room, does your child look at it?',
      'Does your child walk?',
      'Does your child look at things you are looking at?',
      'Does your child make unusual finger movements near his/her face?',
      'Does your child try to attract your attention to his/her own activity?',
      'Have you ever wondered if your child is deaf?',
      'Does your child understand what people say?',
      'Does your child sometimes stare at nothing or wander with no purpose?',
      'Does your child look at your face to check your reaction when faced with something unfamiliar?',
    ];
  }
}
